name = "Zstandard"
uuid = "1affa58d-55fd-4c2a-ac15-0c0ae7390835"
version = "0.1.0"
authors = ["Mark Kittisopikul <markkitt@gmail.com>"]

[deps]
XXHashNative = "e5d8e439-e7fa-4681-9c12-1c64bda517be"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Test = "1.11"
XXHashNative = "1.1"
julia = "1.11"

[sources]
XXHashNative = {url = "https://github.com/mkitti/XXHashNative.jl", rev = "mkitti-XXH64"}

[workspace]
projects = ["test"]
